dist: trusty
sudo: false
language: php

services:
  - docker

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - TEST_COLLECTION=collection-1x.json EZVERSION=1.13.*
  - TEST_COLLECTION=collection-2x.json EZVERSION=2.*

matrix:
  include:
    - php: 7.2
      env: TEST_COLLECTION=collection-2x.json EZVERSION=2.* EXECUTE_DEPLOYMENT=true
  exclude:
    - php: 7.2
      env: TEST_COLLECTION=collection-2x.json EZVERSION=2.*

before_install:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then openssl aes-256-cbc -K $encrypted_91e9470aafb9_key -iv $encrypted_91e9470aafb9_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d; fi
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i
  - docker pull postman/newman_ubuntu1404:latest

script:
  - php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php src/
  - php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php tests/Tests/
  - php vendor/bin/phpunit -c tests/ --exclude-group behat
  - php vendor/behat/behat/bin/behat -c tests/behat.yml
  - php bin/ez-prod init ezsystems/ezplatform $EZVERSION --no-interaction -vvv
  - php bin/ez-prod ps
  - rm -rf ezplatform/var/cache && rm -rf ezplatform/app/cache && docker run --net=host -v $(pwd)/tests/postman:/etc/newman -t postman/newman_ubuntu1404 run $TEST_COLLECTION

after_success:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./scripts/travis_deploy.bash ; fi

notifications:
  email: false
