---
services:

    _defaults:
        autowire: true

    _instanceof:
        eZ\Launchpad\Core\Command:
            tags: [ezlaunchpad.command]

    # Not working in a Phar (method glob() is used but it is not working in a phar)
    #eZ\Launchpad\Command\:
    #    resource: ../src/Command/*

    # then we need to list them manually
    eZ\Launchpad\Command\Rollback: ~
    eZ\Launchpad\Command\Docker\Start: ~
    eZ\Launchpad\Command\Docker\Stop: ~
    eZ\Launchpad\Command\Docker\Up: ~
    eZ\Launchpad\Command\Docker\Clean: ~
    eZ\Launchpad\Command\Docker\Status: ~
    eZ\Launchpad\Command\Docker\Enter: ~
    eZ\Launchpad\Command\Docker\Logs: ~
    eZ\Launchpad\Command\Docker\Update: ~
    eZ\Launchpad\Command\Docker\SymfonyRun: ~
    eZ\Launchpad\Command\Docker\ComposerRun: ~
    eZ\Launchpad\Command\Platformsh\Deploy: ~

    # Self
    eZ\Launchpad\Command\SelfUpdate:
        calls:
            - [setParameters, [ {env: "%app_env%", url: "%ez_phar%", version: "%ez_phar_version%"}] ]

    # Docker
    eZ\Launchpad\Command\Docker\Build:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install' ] ] ]

    eZ\Launchpad\Command\Docker\Initialize:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'ez_install', 'ez_install_solr' ] ] ]

    eZ\Launchpad\Command\Docker\Create:
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'ez_create', 'import_dump', 'ez_install_solr' ] ] ]

    eZ\Launchpad\Command\Docker\DumpData:
        calls:
            - [setRequiredRecipes, [ [ 'create_dump' ] ] ]

    eZ\Launchpad\Command\Docker\ImportData:
        calls:
            - [setRequiredRecipes, [ [ 'import_dump' ] ] ]

    # Platform.sh
    eZ\Launchpad\Command\Platformsh\Setup:
        calls:
            - [setRequiredRecipes, [ [ 'create_dump' ] ] ]
