version: '2.2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/entrypoint.bash:/entrypoint.bash:ro"
            - "${PROJECTCOMPOSEPATH}/ezplatform/doc/nginx/ez_params.d:/etc/nginx/ez_params.d:ro"
        depends_on:
            - engine
        volumes_from:
            - engine:ro
        entrypoint: /entrypoint.bash
        ports:
            - "${PROJECTPORTPREFIX}080:80"
            - "${PROJECTPORTPREFIX}081:81"
        environment:
            - PROJECTMAPPINGFOLDER

    engine:
        build: ./engine/
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/engine/php.ini:/usr/local/etc/php/php.ini:ro"
            - "${PROJECTCOMPOSEPATH}:${PROJECTMAPPINGFOLDER}:rw"
            - "${HOST_COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR}:rw"
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr:/ezsolr:rw"
        shm_size: 754M
        environment:
            - COMPOSER_CACHE_DIR
            - PROJECTMAPPINGFOLDER
            - DEV_UID
            - DEV_GID
            - XDEBUG_ENABLED
            - "XDEBUG_CONFIG=remote_host=172.17.0.1"
            - "PHP_IDE_CONFIG=serverName=ezplatform"
            - "EZP_TEST_REST_HOST=nginx"
            - "DATABASE_PREFIXES=DATABASE"
            - "DATABASE_PLATFORM=mysql"
            - "DATABASE_DRIVER=pdo_mysql"
            - "DATABASE_USER=root"
            - "DATABASE_NAME=ezplatform"
            - "DATABASE_PASSWORD=ezplatform"
            - "SYMFONY_SECRET=eZlaunchpad20Secret09Dev83ModeZ"
            - "APP_SECRET=eZlaunchpad20Secret09Dev83ModeZ"
            - "DATABASE_HOST=db"
            - "CUSTOM_CACHE_POOL=singleredis"
            - "CACHE_HOST=redis"
            - "CACHE_REDIS_PORT=6379"
            - "CACHE_POOL=cache.redis"
            - "CACHE_DSN=redis:6379"
            - "SEARCH_ENGINE=solr"
            - "SOLR_DSN=http://solr:8983/solr"
            - "SYMFONY_TMP_DIR=/tmp/ezplatformcache/"
            - "HTTPCACHE_VARNISH_INVALIDATE_TOKEN=eZlaunchpad20Secret09Varnish"
            - "SESSION_HANDLER_ID=ezplatform.core.session.handler.native_redis"
            - "SESSION_SAVE_PATH=tcp://redis:6379"
    db:
        image: mariadb:10.3
        environment:
            - "MYSQL_ROOT_PASSWORD=ezplatform"
        ports:
            - "${PROJECTPORTPREFIX}306:3306"

    varnish:
        image: plopix/docker-varnish6
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/varnish/varnish.vcl:/etc/varnish/default.vcl:ro"
        ports:
            - "${PROJECTPORTPREFIX}082:80"
        depends_on:
            - nginx

    solr:
        image: solr:7.7
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr/entrypoint.bash:/entrypoint.bash:ro"
        volumes_from:
            - engine:rw
        ports:
            - "${PROJECTPORTPREFIX}983:8983"
        entrypoint: /entrypoint.bash
        depends_on:
            - engine
        environment:
            - DEV_UID
            - DEV_GID
            - PROJECTMAPPINGFOLDER
            - SOLR_CORES=collection1

    # Mailcatcher
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "${PROJECTPORTPREFIX}180:1080"

    # Adminer
    adminer:
        image: adminer:latest
        ports:
            - "${PROJECTPORTPREFIX}084:8080"

    # REDIS
    redis:
        image: redis:latest
        depends_on:
            - engine

    redisadmin:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOST=redis
        ports:
            - "${PROJECTPORTPREFIX}083:8081"

    # Blackfire
    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    # Mysql-Proxy
    mysqlproxy:
        image: plopix/docker-mysqlproxyprofiler
        environment:
        - 'BACKEND=db:3306'
