version: '2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/nginx/entrypoint.bash:/entrypoint.bash:ro"
            - "${PROJECTCOMPOSEPATH}/ezplatform/doc/nginx/ez_params.d:/etc/nginx/ez_params.d:ro"
        depends_on:
            - engine
        volumes_from:
            - engine:ro
        entrypoint: /entrypoint.bash
        ports:
            - "${PROJECTPORTPREFIX}080:80"
            - "${PROJECTPORTPREFIX}081:81"
        environment:
            - PROJECTMAPPINGFOLDER

    engine:
        build: ./engine/
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/engine/php.ini:/usr/local/etc/php/php.ini:ro"
            - "${PROJECTCOMPOSEPATH}:${PROJECTMAPPINGFOLDER}:rw"
            - "${HOST_COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR}:rw"
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr:/ezsolr:rw"
        shm_size: 754M
        environment:
            - COMPOSER_CACHE_DIR
            - PROJECTMAPPINGFOLDER
            - DEV_UID
            - DEV_GID
            - "DATABASE_USER=root"
            - "DATABASE_NAME=ezplatform"
            - "DATABASE_PASSWORD=ezplatform"
            - "SYMFONY_SECRET=eZlaunchpad20Secret09Dev83ModeZ"
            - "DATABASE_HOST=db"
            - "CUSTOM_CACHE_POOL=singlememcached"
            - "CACHE_HOST=memcache"
            - "CACHE_MEMCACHED_PORT=11211"
            - "SEARCH_ENGINE=solr"
            - "SOLR_DSN=http://solr:8983/solr"
            - "HTTPCACHE_PURGE_SERVER=http://varnish:80"
    db:
        image: mariadb:10.2
        environment:
            - "MYSQL_ROOT_PASSWORD=ezplatform"
        ports:
            - "${PROJECTPORTPREFIX}306:3306"

    varnish:
        image: plopix/docker-varnish5
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/varnish/varnish.vcl:/etc/varnish/default.vcl:ro"
        ports:
            - "${PROJECTPORTPREFIX}082:80"
        depends_on:
            - nginx

    solr:
        image: solr:6.4.2
        volumes:
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr:/ezsolr:rw"
            - "${PROJECTCOMPOSEPATH}/${PROVISIONINGFOLDERNAME}/dev/solr/entrypoint.bash:/entrypoint.bash:ro"
            - "${PROJECTCOMPOSEPATH}:${PROJECTMAPPINGFOLDER}:rw"
        ports:
            - "${PROJECTPORTPREFIX}983:8983"
        entrypoint: /entrypoint.bash
        depends_on:
            - engine
        environment:
            - PROJECTMAPPINGFOLDER

    # Mailcatcher
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "${PROJECTPORTPREFIX}180:1080"

    # Adminer
    adminer:
        image: adminer:latest
        ports:
            - "${PROJECTPORTPREFIX}084:8080"

    # MEMCACHE
    memcache:
        image: ilari/alpine-memcached
        depends_on:
            - engine

    memcachedadmin:
        image: plopix/docker-memcacheadmin
        environment:
            - "MEMCACHE_HOST=memcache"
        ports:
            - "${PROJECTPORTPREFIX}083:8080"

    # Blackfire
    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
